global:
  security:
    allowInsecureImages: true
  imageRegistry: ""

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: "latest"
  pullPolicy: IfNotPresent

auth:
  username: admin
  password: secret
  database: user_service

primary:
  initdb:
    scripts:
      init-schemas.sql: |
        CREATE SCHEMA IF NOT EXISTS arm_support;
        CREATE SCHEMA IF NOT EXISTS user_service;
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

architecture: standalone