apiVersion: v1
kind: Secret
metadata:
  name: arm-support-service-secrets
  namespace: arm-support
type: Opaque
stringData:
  # Пароль должен совпадать с postgres-values.yaml → auth.password
  POSTGRES_PASSWORD: secret
